/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Construction: typeof import('./src/components/Construction/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    JQConfirm: typeof import('./src/components/j-q-confirm/index.vue')['default']
    JQConfirmDialog: typeof import('./src/components/j-q-confirm-dialog/index.vue')['default']
    JQDialog: typeof import('./src/components/j-q-dialog/index.vue')['default']
    JQInput: typeof import('./src/components/j-q-input/index.vue')['default']
    JQSelect: typeof import('./src/components/j-q-select/index.vue')['default']
    JQTable: typeof import('./src/components/j-q-table/index.vue')['default']
    JQTooltip: typeof import('./src/components/j-q-tooltip/index.vue')['default']
    Pagination: typeof import('./src/components/j-q-table/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
