/* eslint-disable */
// This file is auto-generated by generate-custom-svg.js
export const myIcons: { [key: string]: string } = {
  'app:clear': 'svg/clear.svg',
  'app:navigation-arrow-left': 'svg/navigation-arrow-left.svg',
  'app:navigation-arrow-right': 'svg/navigation-arrow-right.svg',
  'app:upload': 'svg/upload.svg'
};
