/* eslint-disable */
// This file is auto-generated by generate-custom-svg.js
export const myIcons: { [key: string]: string } = {
  'app:add': 'svg/add.svg',
  'app:banner-info': 'svg/banner-info.svg',
  'app:clear': 'svg/clear.svg',
  'app:collapse': 'svg/collapse.svg',
  'app:complete': 'svg/complete.svg',
  'app:countdown': 'svg/countdown.svg',
  'app:delete': 'svg/delete.svg',
  'app:dropdown': 'svg/dropdown.svg',
  'app:end-time-dark': 'svg/end-time-dark.svg',
  'app:end-time': 'svg/end-time.svg',
  'app:expand': 'svg/expand.svg',
  'app:my-checked': 'svg/my-checked.svg',
  'app:navigation-arrow-left': 'svg/navigation-arrow-left.svg',
  'app:navigation-arrow-right': 'svg/navigation-arrow-right.svg',
  'app:navigation-close': 'svg/navigation-close.svg',
  'app:reset-query': 'svg/reset-query.svg',
  'app:speaker': 'svg/speaker.svg',
  'app:start-time-dark': 'svg/start-time-dark.svg',
  'app:start-time': 'svg/start-time.svg',
  'app:text-to-input-close': 'svg/text-to-input-close.svg',
  'app:text-to-input-confirm': 'svg/text-to-input-confirm.svg',
  'app:topbar-arrow-bottom-white': 'svg/topbar-arrow-bottom-white.svg',
  'app:topbar-arrow-bottom': 'svg/topbar-arrow-bottom.svg',
  'app:upload': 'svg/upload.svg',
  'app:upload2': 'svg/upload2.svg'
};
